version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1
    ports:
      - 5601:5601
    restart: on-failure
    depends_on:
      - elasticsearch
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.12.1
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
    user: root
    restart: on-failure
  jms:
    image: vromero/activemq-artemis
    ports:
      - 8161:8161
      - 61616:61616
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  eureka:
    image: prcompany/mssc-brewery-eureka
    ports:
      - 8761:8761
  config:
    image: prcompany/mssc-config-server
    ports:
      - 8888:8888
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
  inventory-service:
    image: prcompany/mssc-beer-inventory-service
    ports:
      - 8082:8082
    depends_on:
      - eureka
      - config
      - jms
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      SPRING_PROFILES_ACTIVE: docker
      SPRING_ARTEMIS_HOST: jms
      DB_HOST: db
      DB_PORT: 3306
      ZIPKIN_HOST: zipkin
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  beer-service:
    image: prcompany/mssc-beer-service
    ports:
      - 8080:8080
    depends_on:
      - eureka
      - config
      - jms
      - inventory-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      SPRING_PROFILES_ACTIVE: docker
      SPRING_ARTEMIS_HOST: jms
      DB_HOST: db
      DB_PORT: 3306
      ZIPKIN_HOST: zipkin
      beer_inventory_service_host: http://inventory-service:8082
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  order-service:
    image: prcompany/mssc-beer-order-service
    ports:
      - 8081:8081
    depends_on:
      - eureka
      - config
      - jms
      - beer-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      SPRING_PROFILES_ACTIVE: docker
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
      SPRING_ARTEMIS_HOST: jms
      DB_HOST: db
      DB_PORT: 3306
      ZIPKIN_HOST: zipkin
      inventory_beer_service_host: http://beer-service:8080
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  tasting-room-service:
    image: prcompany/mssc-tasting-room
    ports:
      - 8084:8084
    depends_on:
      - eureka
      - config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      SPRING_PROFILES_ACTIVE: docker
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      DB_HOST: db
      DB_PORT: 3306
      ZIPKIN_HOST: zipkin
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  gateway:
    image: prcompany/mssc-brewery-gateway
    ports:
      - 9090:9090
    depends_on:
      - eureka
      - config
      - beer-service
      - inventory-service
      - order-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
    restart: on-failure

